### ISSUE TITLE
Update the substrate-evm addr conversion explanation

### ISSUE THREAD

**Issue by jimmychu0807** [CESSProject/doc-v2#112]
This page: https://docs.cess.cloud/core/developer/guides/substrate-evm

with this diagram:

![Screenshot 2023-12-07 at 10 57 02](https://github.com/CESSProject/doc-v2/assets/898091/b8af036e-5482-4d45-aee3-d70985020a19)

**Comment by jiuquxzy** [comment]
> This page: https://docs.cess.cloud/core/developer/guides/substrate-evm
> 
> with this diagram:
> 
> ![Screenshot 2023-12-07 at 10 57 02](https://private-user-images.githubusercontent.com/898091/288613254-b8af036e-5482-4d45-aee3-d70985020a19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MjIyNTksIm5iZiI6MTcxNjUyMTk1OSwicGF0aCI6Ii84OTgwOTEvMjg4NjEzMjU0LWI4YWYwMzZlLTU0ODItNGQ0NS1hZWUzLWQ3MDk4NTAyMGExOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwMzM5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDJkZDgwOTU2NWMwNmFjM2M5Zjg0ZDJjMDFjNTdhZmRjYjU0Yjk2NGQ3OGI5OThlY2IwOGM2Yjk4ZWVkYjc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JQxrC4B_dlVfxjUJObop9s7MNI057MQdEq-JC6Z7baE)

**Comment by jiuquxzy** [comment]
updated
