### ISSUE TITLE
node.chainWsUrl" is required' with v0.5.5

### ISSUE THREAD

**Issue by seawolf2311** [CESSProject/doc-v2#146]
I meet an issue with v0.5.5 when setup although input "wss://testnet-rpc1.cess.cloud" when run cess config set
"debug: Loading config file: config.yaml
error: failed to load config: '"node.chainWsUrl" is required'
Trace: [Error [ValidationError]: "node.chainWsUrl" is required] {"
![cess](https://github.com/CESSProject/doc-v2/assets/90144902/4fca7f0f-f044-43b0-b4f8-c301b7eb8470)

**Comment by jiuquxzy** [comment]
> I meet an issue with v0.5.5 when setup although input "wss://testnet-rpc1.cess.cloud" when run cess config set "debug: Loading config file: config.yaml error: failed to load config: '"node.chainWsUrl" is required' Trace: [Error [ValidationError]: "node.chainWsUrl" is required] {" ![cess](https://private-user-images.githubusercontent.com/90144902/310021584-4fca7f0f-f044-43b0-b4f8-c301b7eb8470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODM3MDQsIm5iZiI6MTcxMjQ4MzQwNCwicGF0aCI6Ii85MDE0NDkwMi8zMTAwMjE1ODQtNGZjYTdmMGYtZjA0NC00M2IwLWI0ZjgtYzMwMWI3ZWI4NDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA5NTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1OWM5Y2IyYzU2YWI2NjdmYTEyNTMyYzIyOGZlZWYzNGQ2MjI0N2YxOWMzYzI4ZTI4NDQxOWQxYTM1MzI3ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0mRnlK9OLfP-PHOIYqcCBpC7mkNHRj_4fHaBh0Anr-c)

You need to use the cess pullimg command to update the image first
