### ISSUE TITLE
"Quick Experience" Page not found

### ISSUE THREAD

**Issue by hammad93** [CESSProject/doc-v2#169]
Steps to recreate,

1. Navigate to https://cess.cloud/deoss.html
2. Click "Learn more" under DeOSS light
3. Page not found https://docs.cess.cloud/deoss/introduction/quick-experience

I'm sorry if this is a duplicate or not relevant to this repository. I would also like to know if there is a similar page on the documentation.

**Comment by jiuquxzy** [comment]
> Steps to recreate,
> 
> 1. Navigate to https://cess.cloud/deoss.html
> 2. Click "Learn more" under DeOSS light
> 3. Page not found https://docs.cess.cloud/deoss/introduction/quick-experience
> 
> I'm sorry if this is a duplicate or not relevant to this repository. I would also like to know if there is a similar page on the documentation.

Hello, this page has been deleted. There are relevant examples in the specific SDK items below.
