### ISSUE TITLE
Redirection of docs.cess.cloud failed

### ISSUE THREAD

**Issue by jimmychu0807** [CESSProject/doc-v2#183]
Currently https://docs.cess.cloud will redirect to https://docs.cess.cloud/doc-v2, which fail to load. I believe it should redirect to https://docs.cess.cloud/core.

**Comment by sunway910** [comment]
Can use: **https://doc.cess.cloud** to access **https://docs.cess.cloud/core** for now
docs.cess.cloud is a cname to gitbook backend, I can not set https://docs.cess.cloud/ to https://docs.cess.cloud/core

**Comment by jimmychu0807** [comment]
I am happy with the arrangement, so will close it for now. @yeousunn if you have other thought, feel free to open it.
